<div class="page-header container">
    <h1 class="catch"><span class="glyphicon glyphicon-user"></span> <?php echo $this->translate('Sign In'); ?></h1>
</div>

<?php

if (!$this->redirect && isset($_SERVER['HTTP_REFERER']))
{
    /**
     * Check if needs auto-redirect
     */
    $http_referer = parse_url($_SERVER['HTTP_REFERER']);
    $referer = $http_referer['host'];
    if (isset($http_referer['port']))
        $referer .= ':' . $http_referer['port'];
        
    if ($referer == $_SERVER['HTTP_HOST'])
        $this->redirect = $_SERVER['HTTP_REFERER'];
}


$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');

// Workaround for POedit extractor
_('Username or Email');
_('Password');

?>

<div class="container">
    <div class="content">

        <div class="row-fluid">

            <?php echo $this->form()->openTag($form) ?>

                <dl class="zend_form">
                    <?php echo $this->formElementErrors($form->get('identity')) ?>

                    <div class="input-group input-group-lg">
                        <span class="input-group-addon login"><?php echo _('Username or Email') ?></span>
                        <?php echo $this->formInput($form->get('identity')->setAttribute('class','form-control')) ?>
                    </div>

                    <div class="input-group input-group-lg">
                        <span class="input-group-addon login"><?php echo _('Password') ?></span>
                        <?php echo $this->formInput($form->get('credential')->setAttribute('class','form-control')) ?>
                    </div>

                    <?php if ($this->redirect): ?>
                        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                    <?php endif ?>

                    <dd><?php echo $this->formButton($form->get('submit')->setAttribute('class','btn btn-primary fullwidth')) ?></dd>
                </dl>

            <?php echo $this->form()->closeTag() ?>
 
            <?php if ($this->enableRegistration) : ?>
                
            <a class="btn btn-warning fullwidth" href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Not registered?'); ?> <?php echo $this->translate('Sign up!'); ?></a>
            <?php endif; ?>

        </div>
    
    </div>
</div>
