<div class="container">
	<div class="content">
	
		<div class="page-header">
			<h1 class="catch"><?php echo $this->translate('Conferences management'); ?></h1>
		</div>

		<div class="row-fluid down-space" style="text-align:right;">
			<a class="btn btn-large btn-primary span4 offset4" href="<?php echo $this->url('admin/conferences', array('action' => 'add')); ?>"><span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Create conference'); ?></a>
		</div>
		<div class="row-fluid">
			<table class="table table-striped table-bordered">
				<tr>
					<th><?php echo $this->translate('Name'); ?></th>
					<th><?php echo $this->translate('Created by'); ?></th>
					<th><?php echo $this->translate('Manage'); ?></th>
				</tr>
				<?php foreach ($conferences as $conference): ?>
				<tr>
					<td class="span8"><?php echo $conference->name; ?></td>
					<td><?php echo $conference->user_id; ?></td>
					<td>
						<div class="btn-group">
							<?php
								// Get translations
								$schedule		= $this->translate('Schedule');
								$tracks			= $this->translate('Tracks');
								$submissions	= $this->translate('Submissions'); 
								$staff			= $this->translate('Staff');
								$atendees		= $this->translate('Attendees');
								$edit			= $this->translate('Edit');
								$remove			= $this->translate('Remove');
							?>
							<!-- Schedule -->
							<?php /* <a class="btn btn-small" href="<?php echo $this->url('admin/conferences', array('action' => 'schedule', 'id' => $conference->conference_id)); ?>" rel="tooltip" alt="<?php echo $schedule; ?>" title="<?php echo $schedule; ?>"><i class="glyphicon glyphicon-calendar"></i></a>
							<!-- Tracks -->
							<a class="btn btn-small" href="<?php echo $this->url('admin/conferences', array('action' => 'tracks', 'id' => $conference->conference_id)); ?>" alt="<?php echo $tracks; ?>" title="<?php echo $tracks; ?>"><i class="glyphicon glyphicon-road"></i></a>
							<!-- Submissions -->
							<a class="btn btn-small" href="<?php echo $this->url('admin/conferences', array('action' => 'submissions', 'id' => $conference->conference_id)); ?>" alt="<?php echo $submissions; ?>" title="<?php echo $submissions; ?>"><i class="glyphicon glyphicon-file"></i></a>
							<!-- Staff -->
							<a class="btn btn-small" href="<?php echo $this->url('admin/conferences', array('action' => 'staff', 'id' => $conference->conference_id)); ?>" alt="<?php echo $staff; ?>" title="<?php echo $staff; ?>"><i class="glyphicon glyphicon-eye-open"></i></a>
							<!-- Atendees -->
							<a class="btn btn-small" href="<?php echo $this->url('admin/conferences', array('action' => 'attendees', 'id' => $conference->conference_id)); ?>" alt="<?php echo $atendees; ?>" title="<?php echo $atendees; ?>"><i class="glyphicon glyphicon-user"></i></a> */ ?>
							<!-- Edit -->
							<a class="btn btn-small" href="<?php echo $this->url('admin/conferences', array('action' => 'edit', 'id' => $conference->conference_id)); ?>" alt="<?php echo $edit; ?>" title="<?php echo $edit; ?>"><i class="glyphicon glyphicon-pencil"></i></a>
							<!-- Remove -->
							<a class="btn btn-small" onclick='if(!window.confirm("Are you sure you want to delete this conference?")){return false;}' href="<?php echo $this->url('admin/conferences', array('action' => 'del', 'id' => $conference->conference_id)); ?>" alt="<?php echo $remove; ?>" title="<?php echo $remove; ?>"><i class="glyphicon glyphicon-trash"></i></a>
						</div>
					</td>
				</tr>
				<?php endforeach; ?>
			</table>
		</div>
	</div>
	
</div>