<div class="container">
	<div class="content">
	
		<div class="page-header">
			<h1 class="catch"><?php echo $this->translate('Users management'); ?></h1>
		</div>

		<div class="row-fluid">
			<table class="table table-striped table-bordered">
				<tr>
					<th style="width:40px;"></th>
					<th><?php echo $this->translate('Username'); ?></th>
					<th><?php echo $this->translate('Email'); ?></th>
					<th><?php echo $this->translate('Display Name'); ?></th>
					<th><?php echo $this->translate('Manage'); ?></th>
				</tr>
				<?php foreach ($users as $user): ?>
				<tr>
					<td><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail())->setImgSize(40) ?></td>
					<td><?php echo $user->username; ?></td>
					<td><?php echo $user->email; ?></td>
					<td><?php echo $user->display_name; ?></td>
					<td>
						<div class="btn-group">
							<?php
								// Get translations
								$edit			= $this->translate('Edit');
								$remove			= $this->translate('Remove');
							?>
							<!-- Edit -->
							<?php /*<a class="btn btn-small" href="<?php echo $this->url('admin/users', array('action' => 'edit', 'id' => $user->user_id)); ?>" alt="<?php echo $edit; ?>" title="<?php echo $edit; ?>"><i class="glyphicon glyphicon-pencil"></i></a>
							<a class="btn btn-small" href="<?php echo $this->url('admin/users', array('action' => 'del', 'id' => $user->user_id)); ?>" alt="<?php echo $remove; ?>" title="<?php echo $remove; ?>"><i class="glyphicon glyphicon-trash"></i></a> */ ?>
						</div>
					</td>
				</tr>
				<?php endforeach; ?>
			</table>
		</div>
	</div>
	
</div>